# Generated by Django 4.2.16 on 2024-12-13 10:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reels.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='Tag')),
                ('slug', models.SlugField(default=uuid.uuid1, unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ReelModel',
            fields=[
                ('reel_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reel_video', models.FileField(upload_to=reels.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])], verbose_name='Reel')),
                ('reel_cover', models.FileField(upload_to=reels.models.user_cover_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])], verbose_name='Cover')),
                ('reel_description', models.TextField(blank=True, null=True)),
                ('reel_likes', models.IntegerField(default=0)),
                ('reel_upload_date', models.DateField(auto_now_add=True)),
                ('reel_tags', models.ManyToManyField(related_name='tags', to='reels.tag')),
                ('user_reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reel_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
