# Generated by Django 4.2.16 on 2024-12-13 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reelmodel',
            old_name='user_reel',
            new_name='user',
        ),
    ]
