# Generated by Django 4.2.16 on 2025-01-13 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reels', '0003_reelcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReelLikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_likes', to='reels.reelmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
