# Generated by Django 4.2.16 on 2025-01-14 11:14

import django.core.validators
from django.db import migrations, models
import reels.models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0004_reellikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelmodel',
            name='reel_cover',
            field=models.ImageField(upload_to=reels.models.user_directory_path, verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='reelmodel',
            name='reel_video',
            field=models.FileField(upload_to=reels.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'MOV'])], verbose_name='Reel'),
        ),
    ]
