# Generated by Django 4.2.16 on 2025-01-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0005_alter_reelmodel_reel_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelmodel',
            name='is_close_friends',
            field=models.BooleanField(default=False),
        ),
    ]
