# Generated by Django 4.2.16 on 2025-01-22 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0006_reelmodel_is_close_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reelmodel',
            old_name='is_close_friends',
            new_name='is_close',
        ),
    ]
