# Generated by Django 4.2.16 on 2025-01-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_follow_id_alter_likes_id_alter_stream_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_close_friends',
            field=models.BooleanField(default=False),
        ),
    ]
