# Generated by Django 4.2.16 on 2025-01-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_is_close_friends'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_close_friends',
            new_name='is_close',
        ),
    ]
