# Generated by Django 4.2.16 on 2025-01-13 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reels', '0004_reellikes'),
        ('post', '0006_alter_follow_id_alter_likes_id_alter_stream_id_and_more'),
        ('notification', '0005_alter_notification_options_alter_notification_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='post_notifications', to='post.post'),
        ),
        migrations.AlterField(
            model_name='reelnotification',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reel_notifications', to='reels.reelmodel'),
        ),
    ]
