# Generated by Django 4.2.16 on 2025-01-13 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_follow_id_alter_likes_id_alter_stream_id_and_more'),
        ('notification', '0006_alter_notification_post_alter_reelnotification_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_notifications', to='post.post'),
        ),
    ]
