# Generated by Django 4.2.16 on 2025-01-16 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_follow_id_alter_likes_id_alter_stream_id_and_more'),
        ('authy', '0008_alter_profile_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseFrens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friendProf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_friend', to='post.follow')),
            ],
        ),
    ]
